# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API

    OpenAPI spec version: 1.0.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import mailmojo
from mailmojo.rest import ApiException
from mailmojo.apis.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ ContactsApi unit test stubs """

    def setUp(self):
        self.api = mailmojo.apis.contacts_api.ContactsApi()

    def tearDown(self):
        pass

    def test_get_contacts(self):
        """
        Test case for get_contacts

        Retrieve all contacts across every list.
        """
        pass

    def test_get_subscriber_on_list_by_email(self):
        """
        Test case for get_subscriber_on_list_by_email

        Retrieve a subscriber.
        """
        pass

    def test_get_subscribers_on_list(self):
        """
        Test case for get_subscribers_on_list

        Retrieve subscribers on a list.
        """
        pass

    def test_import_subscribers_to_list(self):
        """
        Test case for import_subscribers_to_list

        Subscribe contacts to the email list.
        """
        pass

    def test_subscribe_contact_to_list(self):
        """
        Test case for subscribe_contact_to_list

        Subscribe a contact to the email list.
        """
        pass

    def test_unsubscribe_contact_on_list_by_email(self):
        """
        Test case for unsubscribe_contact_on_list_by_email

        Unsubscribe a contact.
        """
        pass


if __name__ == '__main__':
    unittest.main()
