# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mailmojo
from mailmojo.api.lists_api import ListsApi  # noqa: E501
from mailmojo.rest import ApiException


class TestListsApi(unittest.TestCase):
    """ListsApi unit test stubs"""

    def setUp(self):
        self.api = mailmojo.api.lists_api.ListsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_list_by_id(self):
        """Test case for get_list_by_id

        Retrieve an email list.  # noqa: E501
        """
        pass

    def test_get_lists(self):
        """Test case for get_lists

        Retrieve all email lists.  # noqa: E501
        """
        pass

    def test_update_list(self):
        """Test case for update_list

        Update an email list partially.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
