# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API

    OpenAPI spec version: 1.0.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import mailmojo
from mailmojo.rest import ApiException
from mailmojo.apis.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """ AccountsApi unit test stubs """

    def setUp(self):
        self.api = mailmojo.apis.accounts_api.AccountsApi()

    def tearDown(self):
        pass

    def test_create_account(self):
        """
        Test case for create_account

        Create an account.
        """
        pass

    def test_get_account_by_username(self):
        """
        Test case for get_account_by_username

        Retrieve account details.
        """
        pass

    def test_update_account(self):
        """
        Test case for update_account

        Update account details.
        """
        pass


if __name__ == '__main__':
    unittest.main()
