# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API

    OpenAPI spec version: 1.0.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.contact import Contact
from .models.contact_list_associations import ContactListAssociations
from .models.contacts import Contacts
from .models.embed import Embed
from .models.embed_options import EmbedOptions
from .models.import_result import ImportResult
from .models.list import List
from .models.minimal_user import MinimalUser
from .models.subscriber import Subscriber
from .models.user import User

# import apis into sdk package
from .apis.accounts_api import AccountsApi
from .apis.contacts_api import ContactsApi
from .apis.embed_api import EmbedApi
from .apis.lists_api import ListsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
